---
- name: Kill all previous hadoop services if any
  shell: "jps | grep -v Jps | awk '{print $1}' | xargs kill -9 > /dev/null"
  ignore_errors: yes


- name: Copy startup script
  template:
    src: service-start-cluster.j2
    dest: "{{ startup_script_init }}"
    mode: 0755
  args:
    creates: '{{ startup_script_init }}'
  ignore_errors: True


- include: service_hadoop.yml
- include: service_hive.yml
- include: service_spark.yml
