---

- name: Check if NodeJs module is executed
  stat: path={{ nodestat }}
  register: nodestatflag


- block:
  - include: download.yml
    environment:
      "{{ proxy_env }}"

  - name: Create Node Dir
    file: path={{ node_install_path }} state=directory owner=root group=root mode=0755

  - name: Extract NodeJs
    unarchive: src={{ node_local_path }} dest={{ node_install_path }} remote_src=yes owner=root group=root mode=0755

  - name: Set Node Vars
    template: src=node_path.j2 dest={{ node_profile_path }} mode=0755

  - name: Cleaning any previous NPM http proxy
    shell: "source /etc/profile && npm config delete http-proxy -g"
    args:
     executable: /bin/bash

  - name: Cleaning any previous NPM https proxy
    shell: "source /etc/profile && npm config delete https-proxy -g"
    args:
     executable: /bin/bash

  - name: Set NPM http proxy
    shell: "sudo su - root -c 'source /etc/profile && npm config set http-proxy http://{{ proxy_user }}:{{ proxy_passwd }}@{{ proxy_server }}:{{ proxy_port }} -g'"
    args:
      executable: /bin/bash
    when: proxy_optional

  - name: Set NPM https proxy
    shell: "sudo su - root -c 'source /etc/profile && npm config set https-proxy http://{{ proxy_user }}:{{ proxy_passwd }}@{{ proxy_server }}:{{ proxy_port }} -g'"
    args:
     executable: /bin/bash
    when: proxy_optional

  - name: Install NPM modules
    shell: "sudo su - root -c 'npm install {{ item.name }}{{ item.version }} -g'"
    args:
     chdir: "{{ node_install_path }}/{{ node_expanded_version }}"
     executable: /bin/bash
    with_items:
      - { name: 'stylus', version: '@0.54.5' }
      - { name: 'babel-cli', version: '@6.26.0' }
      - { name: 'babel-preset-es2015', version: '@6.24.1' }
      - { name: 'karma', version: '@1.4.1' }
      - { name: 'karma-jasmine', version: '@1.1.0' }
      - { name: 'karma-chrome-launcher', version: '@2.2.0' }
      - { name: 'jasmine-core', version: '@2.5.2' }
      - { name: 'karma-cli', version: '@1.0.1' }
      - { name: 'karma-chrome-launcher', version: '@2.2.0' }
      - { name: 'karma-coverage', version: '@1.1.1' }
      - { name: 'karma-requirejs', version: '@1.1.0' }
      - { name: 'requirejs', version: '@2.3.5' }
      - { name: 'webdriverio', version: '@4.9.11' }
      - { name: 'mocha', version: '@3.5.3' }
      - { name: 'mocha-multi', version: '@1.0.1' }
      - { name: 'mochawesome', version: '@3.0.2' }
      - { name: 'selenium-standalone', version: '@latest' }
      - { name: 'request', version: '@latest' }
      - { name: 'js-yaml', version: '@latest' }
      - { name: 'fs', version: '@latest' }
      - { name: 'git+https://git@github.com/prashantsail/CodeceptJS#80e8f28', version: '' }

  - name: Remove NPM http proxy
    shell: "source /etc/profile && npm config delete http-proxy -g"
    args:
     executable: /bin/bash

  - name: Remove NPM https proxy
    shell: "source /etc/profile && npm config delete https-proxy -g"
    args:
     executable: /bin/bash

  - name: Install selenium (Bypassing since failures are persistent)
    shell: "sudo su - root -c 'selenium-standalone install'"
    args:
     executable: /bin/bash
    environment:
      "{{ proxy_env }}"
    ignore_errors: yes

  - file: path={{ nodestat }} state=touch
  when: not nodestatflag.stat.exists
