---
- name: Gathering Facts
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
  - block:
    - name: Setting proxy
      set_fact:
        proxy_env: {
                   "https_proxy": "https://{{ proxy_user }}:{{ proxy_passwd }}@{{ proxy_server }}:{{ proxy_port }}",
                   "http_proxy": "http://{{ proxy_user }}:{{ proxy_passwd }}@{{ proxy_server }}:{{ proxy_port }}"
                 }
    when: proxy_optional


- name: Prepare to download Hadoop packages
  hosts: hadoop_clients
  become: yes
  become_method: sudo
  roles:
  - download
  environment:
    "{{ proxy_env }}"

- name: Setup Hadoop prerequesite
  hosts: hadoop_clients
  become: yes
  become_method: sudo
  roles:
  - prep

- name: Stop existing Hadoop services
  hosts: hadoop_clients
  become: yes
  become_method: sudo
  roles:
  - stopHadoop

- name: Setup Hadoop
  hosts: hadoop_namenode
  become: yes
  become_method: sudo
  roles:
  - hadoop

- name: Setup hive
  hosts: hive
  become: yes
  become_method: sudo
  roles:
  - hive


- name: Setup Scala
  hosts: hadoop_clients
  become: yes
  become_method: sudo
  roles:
  - scala


- name: Setup Spark
  hosts: spark_master
  become: yes
  become_method: sudo
  roles:
  - spark

- name: Stop existing Hadoop services
  hosts: hadoop_clients
  become: yes
  become_method: sudo
  roles:
  - stopHadoop

- name: Start Hadoop services
  hosts: hadoop_clients
  become: yes
  become_method: sudo
  roles:
  - startHadoop
