---
#- hosts: all
#  gather_facts: False
#  pre_tasks:
#   - setup:
#       filter: ansible_*

- name: Initalize playbook
  hosts: all
  gather_facts: False
  become: yes
  become_method: sudo

  tasks:
  - block:
    - name: Setting proxy
      set_fact:
        proxy_env: {
                   "https_proxy": "https://{{ proxy_user }}:{{ proxy_passwd }}@{{ proxy_server }}:{{ proxy_port }}",
                   "http_proxy": "http://{{ proxy_user }}:{{ proxy_passwd }}@{{ proxy_server }}:{{ proxy_port }}"
                 }
    when: proxy_optional


- name: Gathering Facts
  hosts: all
  gather_facts: True
  become: yes
  become_method: sudo

- name: Install prerequisites
  hosts: all
  become: yes
  become_method: sudo
  roles:
  - prep


- name: Download prerequisites on Web server
  hosts: webserver
  serial: 1
  become: yes
  become_method: sudo
  roles:
  - downloads


- name: Setup machine prerequisites on webserver
  hosts: webserver
  become: yes
  become_method: sudo
  remote_user: root
  environment:
    "{{ proxy_env }}"
  roles:
  - pip


- name: Download Python prerequisites on hadoop cluster
  hosts: hadoop_cluster
  serial: 1
  become: yes
  become_method: sudo
  roles:
  - downloads
  vars:
    setup_anaconda : false


- name: Install Python prerequisites on hadoop cluster
  hosts: hadoop_cluster
  become: yes
  become_method: sudo
  roles:
  - python
  vars:
    setup_anaconda : false


- name: Install Git
  hosts: git_client
  become: yes
  become_method: sudo
  roles:
    - { role: git, when: setup_git }


- name: Install JDK
  hosts: hadoop_clients
  become: yes
  become_method: sudo
  roles:
  - jdk

- name: Install Monit
  hosts: webserver
  become: yes
  become_method: sudo
  roles:
    - { role: monit, when: setup_monit }

- name: Install R
  hosts: all
  become: yes
  become_method: sudo
  environment:
    "{{ proxy_env }}"
  roles:
    - { role: R, when: setup_r }

- name: Install Google Chrome
  hosts: webserver
  become: yes
  become_method: sudo
  remote_user: root
  environment:
    "{{ proxy_env }}"
  roles:
    - { role: google-chrome, when: setup_google_chrome }
