---
- name: Get the JAVA_HOME values
  shell: "source /etc/profile && echo $JAVA_HOME"
  args:
     executable: /bin/bash
  register: java_home

- debug: msg="{{java_home}}"

######################## Creating warehouse directory for hive ############################################
- name: create /usr/hive/warehouse directory
  shell: "source /etc/profile && {{ hadoop_dir }}/{{ hadoop_expended_version }}/bin/hadoop fs -mkdir -p /usr/hive/warehouse"
  args:
     executable: /bin/bash
#  environment:
#    JAVA_HOME: "{{java_home.stdout}}"


- name: Changing permission to /usr/hive/warehouse directory
  shell: "source /etc/profile && {{ hadoop_dir }}/{{ hadoop_expended_version }}/bin/hadoop fs -chmod g+w /usr/hive/warehouse"
  args:
     executable: /bin/bash
#  environment:
#    JAVA_HOME: "{{java_home.stdout}}"
##########################################################################################################
