---
- name: Copy Hive Metastore service script
  template:
    src: metastore-service.j2
    dest: "{{ systemd_services_dir }}/metastore.service"

- name: Copy Hive Server2 service script
  template:
    src: hiveserver2-service.j2
    dest: "{{ systemd_services_dir }}/hiveserver2.service"
  
- name: Copy Hive Metastore Monit service
  template:
    src: monit-metastore.j2
    dest: /etc/monit.d/service-metastore
  when: setup_monit

- name: Copy Hive Server2 Monit service
  template:
    src: monit-hive-server2.j2
    dest: /etc/monit.d/service-hive-server2
  when: setup_monit

- name: Start Hive Metastore service
  service:
    name: metastore
    state: started

- name: Start Hive Server2 service
  service:
    name: hiveserver2
    state: started

- name: Enable Metastore service
  service:
    name: metastore
    enabled: yes
  when: setup_monit

- name: Enable Hive Server2 service
  service:
    name: hiveserver2
    enabled: yes
  when: setup_monit
